[package]
name = "clickhouse-test-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clickhouse-arrow = { path = "../clickhouse-arrow", features = ["test-utils", "derive", "serde"] }
anyhow = "1.0"
bytes = "1.0"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde-transcode = "1.0"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
atty = "0.2"
hex = "0.4"
ratatui = "0.29"
crossterm = "0.28"
tui-textarea = "0.7"
sqlformat = "0.3"
dirs = "5.0"
chrono = "0.4"
arboard = "3.4"
sha2 = "0.10"
zip = "2.1"
lz4_flex = "0.11"

[features]
default = []
